### PR TITLE
Add wpuseo__get_metas__description filter

### PR DESCRIPTION
**Pull request by JulioPotier**
Forgot to push this one -_-' thanks

### CODE REVIEW

**Comment by JulioPotier** [comment]
Hey @Darklg could you? Thanks :)

**Comment by Darklg** [comment]
@JulioPotier added two filters directly in the function, as it is called at multiple places.

**Comment by JulioPotier** [comment]
Ok add those, but it's not the same.
My filter will be used 1 time in the case of an empty description (which happened) so I can hook in and fill it.
With your solution, my callback will be called for every case where prepare_text is called.
This is not the same :/

**Comment by Darklg** [comment]
@JulioPotier yours is triggered directly before the function call, and just in this condition : 
```php
(!is_home() && !is_front_page() && (is_single() || is_page() || is_singular() || $this->is_shop() || $this->is_admin_preview()))
```
So the content will necessarily go into the function, and your fix will not be called on front page, a category, etc, because the prepare_text is called at multiple places which won't get the filter.

If the new filters are used, the fix can be triggered only if the description is empty : 

```php
<?php
add_action('wpuseo__prepare_text__before','_wpuseo__prepare_text__before', 10, 2);
function _wpuseo__prepare_text__before($text){
    $text = trim($text);
    if(empty($text) and $your_template_condition){
        $text = 'my default value';
    }
    return $text;
}
```

**Comment by JulioPotier** [comment]
Ok I'll test it, thanks :)

**Pull request closed without merging**
